name: release

defaults:
  run:
    shell: bash

on:
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

env:
  preview: ${{ github.event_name == 'push' || github.repository != 'ongyx/yak-shaving' }}

jobs:
  update-submodules:
    name: Update Submodules
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      updated: $[{ steps.check.outputs.updated }]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules
        run: |
          git submodule update --recursive --init
          git submodule update --recursive --remote

      - name: Check updated submodules
        id: check
        run: |
          declare -a updated

          while read -r line; do
              sha="$(echo "$line" | cut -d' ' -f1)"
              name="$(echo "$line" | cut -d' ' -f2)"
              if [[ "$sha" == +* ]]; then
                  updated+=("$name")
              fi
          done < <(git submodule status)

          echo "updated=${updated[@]}" >> "$GITHUB_OUTPUT"

      # https://stackoverflow.com/a/68213855
      - name: Commit updated submodules
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add --all
          git commit -m "Update submodules" || echo "No updates to submodules"
          git push

  build-helix:
    name: Build Helix (Steel fork)
    needs: [update-submodules]
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(needs.update-submodules.outputs.updated, 'submodules/helix') }}
    uses: ./.github/workflows/build-helix.yml

  build-steel:
    name: Build Steel
    needs: [update-submodules]
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(needs.update-submodules.outputs.updated, 'submodules/steel') }}
    uses: ./.github/workflows/build-steel.yml
